export const NAV_DATA = [
  {
    name: "Medical Scrubs",
    id: 1,
    category: [
      "Shop All Scrubs",
      "Scrub Tops",
      "Scrub Pants",
      "Scrub Sets",
      "Lab Coats",
      "Scrub Jackets",
      "Scrub Dresses",
      "Scrub Shorts",
    ],
    featured: ["New Arrivals", "Best Sellers", "Plus Size", "Custom Orders"],
    More: ["Bulk Orders", "Hospital Partnerships", "Custom Embroidery", "Size Guide"],
    nameCat: "Categories",
    nameFeat: "Featured",
    nameMore: "Services",
    imageData: [
      "/new/Collection/FA-SoochuhWeb-029-copy.jpg",
      "/new/Collection/FA-SoochuhWeb-170-copy.jpg",
    ],
    imageDescription: ["Scrub Tops", "Plus Size"],
  },
  {
    name: "New Arrivals",
    id: 2,
    category: [
      "Shop All",
      "Scrub Tops",
      "Scrub Pants",
      "Scrub Sets",
      "Lab Coats",
      "Scrub Jackets",
      "Scrub Dresses",
      "Scrub Shorts",
    ],
    featured: ["Plus Size", "Spring Collection", "Trending"],

    nameCat: "Categories",
    nameFeat: "Trending",
    imageData: [
      "/new/Collection/FA-SoochuhWeb-277-copy.jpg",
      "/new/Collection/FAAM-ART-SoochuhWeb-3400-copy.jpg",
      "/new/Best Sellers/FA-SoochuhWeb-087-copy-1.jpg",
    ],
    imageDescription: ["Spring Collection", "Scrub Tops", "Scrub Dresses"],
  },
  {
    name: "Scrub of the Week",
    id: 3,
    category: [
      "Shop All",
      "Scrub Tops",
      "Scrub Pants",
      "Scrub Sets",
      "Lab Coats",
      "Scrub Jackets",
      "Scrub Dresses",
      "Scrub Shorts",
    ],
    nameCat: "Categories",
    nameFeat: "Trending",
    imageData: [
      "/new/Scrub of the Week/FA-SoochuhWeb-029-copy.jpg",
      "/new/Scrub of the Week/FA-SoochuhWeb-036-copy-1.jpg",
    ],
    imageDescription: ["Scrub Tops", "Scrub Dresses"],
  },
  {
    name: "Plus Size",
    id: 4,
    category: [
      "Shop All",
      "Scrub Tops",
      "Scrub Pants",
      "Scrub Sets",
      "Lab Coats",
      "Scrub Jackets",
      "Scrub Dresses",
      "Scrub Shorts",
    ],
    nameCat: "Categories",
    imageData: [
      "/new/Best Sellers/FA-SoochuhWeb-098-copy-1.jpg",
      "/new/Best Sellers/FA-SoochuhWeb-138-copy.jpg",
      "/new/Collection/FA-SoochuhWeb-170-copy.jpg",
    ],
    imageDescription: ["Scrub Pants", "Scrub Dresses", "Scrub Tops"],
  },
  {
    name: "About Us",
    id: 5,
    category: [
      "Our Mission",
      "Quality Standards",
      "Materials",
      "Manufacturing",
      "Care Instructions",
      "Our Team",
    ],
    nameCat: "About",
    imageData: [
      "/new/Follow Us/FA-Soochuh-Scrubs-Web-6694-OPT.jpg",
      "/new/Follow Us/FA-Soochuh-Scrubs-Web-6964-OPT.jpg",
    ],
  },
];
